blank_issues_enabled: false
contact_links:
  - name: Tiny Helpdesk Hero Discussion
    url: https://github.com/sandgraal/tiny-helpdesk-hero/discussions
    about: Ask questions or share ideas that aren’t actionable issues.
